/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xmoieo_silk_SilkCoder */

#ifndef _Included_com_xmoieo_silk_SilkCoder
#define _Included_com_xmoieo_silk_SilkCoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xmoieo_silk_SilkCoder
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_xmoieo_silk_SilkCoder_decode
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

/*
 * Class:     com_xmoieo_silk_SilkCoder
 * Method:    encode
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_xmoieo_silk_SilkCoder_encode
  (JNIEnv *, jclass, jstring, jstring, jboolean, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
